# Generated by Django 3.2.4 on 2021-06-13 06:40

from django.db import migrations

from tasks_app.generate_data import *


def generate_records(apps, schema_editor):
    Task = apps.get_model('tasks_app', 'Task')

    for _ in range(200):
        new_task = Task(
            user_name=gen_rand_word(),
            email=gen_rand_email(),
            task_text=gen_rand_text()
        )
        new_task.save()


class Migration(migrations.Migration):
    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_records),
    ]
